routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//category routes
Route::get('/categories/{category}/general_overview', 'CategoryController@generalOverview')->name('categories.general_overview');
Route::resource('categories', 'CategoryController')->only(['index']);

//article routes
Route::resource('articles', 'ArticleController')->only(['index', 'show']);

//contact us request routes
Route::resource('contact_us_requests', 'ContactUsRequestController')->only(['store']);

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Article extends Model
{
    use HasFactory;

    protected $fillable = ['category_id', 'title', 'body', 'image', 'file', 'time_to_read', 'status', 'views_count'];
    protected $appends = ['file_path', 'image_path'];

    //attr
    public function getFilePathAttribute()
    {
        return Storage::url('uploads/' . $this->file);

    }// end of getFilePathAttribute

    public function getImagePathAttribute()
    {
        return Storage::url('uploads/' . $this->image);

    }// end of getFilePathAttribute

    //scope
    public function scopeWhenStatus($query, $status)
    {
        return $query->when($status, function ($q) use ($status) {

            return $q->where('status', $status);

        });

    }// end of scopeWhenStatus

    public function scopeWhenCategoryId($query, $categoryId)
    {
        return $query->when($categoryId, function ($q) use ($categoryId) {

            return $q->where('category_id', $categoryId);

        });

    }// end of scopeWhenCategoryId

    public function scopeWhenSearch($query, $search)
    {
        return $query->when($search, function ($q) use ($search) {

            return $q->where('title', 'like', "%$search%");

        });

    }// end of scopeWhenSearch

    //rel
    public function category()
    {
        return $this->belongsTo(Category::class);

    }// end of category

}//end of model

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ArticleRequest;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class ArticleController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read_articles')->only(['index']);
        $this->middleware('permission:create_articles')->only(['create', 'store']);
        $this->middleware('permission:update_articles')->only(['edit', 'update']);
        $this->middleware('permission:delete_articles')->only(['delete', 'bulk_delete']);

    }// end of __construct

    public function index()
    {
        return view('admin.articles.index');

    }// end of index

    public function data()
    {
        $articles = Article::whenStatus(request()->status)
            ->whenCategoryId(request()->category_id)
            ->select();

        return DataTables::of($articles)
            ->addColumn('record_select', 'admin.articles.data_table.record_select')
            ->addColumn('status', 'admin.articles.data_table.status')
            ->editColumn('created_at', function (Article $article) {
                return $article->created_at->format('Y-m-d');
            })
            ->addColumn('actions', 'admin.articles.data_table.actions')
            ->rawColumns(['record_select', 'status', 'actions'])
            ->toJson();


    }// end of data

    public function create()
    {
        $categories = Category::all();

        return view('admin.articles.create', compact('categories'));

    }// end of create

    public function store(ArticleRequest $request)
    {
        $requestData = $request->validated();

        if ($request->file) {
            $request->file->store('public/uploads');
            $requestData['file'] = $request->file->hashName();
        }

        if ($request->image) {
            $request->image->store('public/uploads');
            $requestData['image'] = $request->image->hashName();
        }

        Article::create($requestData);

        session()->flash('success', __('site.added_successfully'));
        return redirect()->route('admin.articles.index');

    }// end of store

    public function show(Article $article)
    {
        return view('admin.articles.show', compact('article'));

    }// end of show

    public function edit(Article $article)
    {
        $categories = Category::all();

        return view('admin.articles.edit', compact('categories', 'article'));

    }// end of edit

    public function update(ArticleRequest $request, Article $article)
    {
        $requestData = $request->validated();

        if ($request->file) {
            Storage::disk('local')->delete('public/uploads/' . $article->file);
            $request->file->store('public/uploads');
            $requestData['file'] = $request->file->hashName();
        }

        if ($request->image) {
            Storage::disk('local')->delete('public/uploads/' . $article->image);
            $request->image->store('public/uploads');
            $requestData['image'] = $request->image->hashName();
        }

        $article->update($requestData);

        session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('admin.articles.index');

    }// end of update

    public function destroy(Article $article)
    {
        $this->delete($article);
        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('admin.articles.index');

    }// end of destroy

    public function bulkDelete()
    {
        foreach (json_decode(request()->record_ids) as $recordId) {

            $article = Article::FindOrFail($recordId);
            $this->delete($article);

        }//end of for each

        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('admin.articles.index');

    }// end of bulkDelete

    private function delete(Article $article)
    {
        $article->delete();

    }// end of delete

}///end of controller

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Category;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::whenCategoryId(request()->category_id)
            ->whenSearch(request()->search)
            ->where('status', 'published')
            ->paginate(10);

        $this->incrementCategoryViews();

        $category = null;
        $otherCategories = null;

        if (request()->category_id) {

            $category = Category::FindOrFail(request()->category_id);

            $otherCategories = Category::where('id', '!=', $category->id)->limit(4)->get();

        }

        return view('articles.index', compact('category', 'articles', 'otherCategories'));

    }// end of index

    public function show(Article $article)
    {
        $this->incrementArticleViews($article);
        return view('articles.show', compact('article'));

    }// end of show

    private function incrementCategoryViews()
    {
        if (request()->category_id) {
            $category = Category::FindOrFail(request()->category_id);
            $category->increment('views_count');
        }

    }// end of incrementCategoryViews

    private function incrementArticleViews(Article $article)
    {
        $article->increment('views_count');

    }// end of incrementCategoryViews

}//end of controller

resources/views/admin/articles/create.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2 pt-2">@lang('articles.articles')</h2>

    <ul class="breadcrumb my-2">
        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.articles.index') }}">@lang('articles.articles')</a></li>
        <li class="breadcrumb-item">@lang('site.create')</li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <form method="post" action="{{ route('admin.articles.store') }}" enctype="multipart/form-data">
                        @csrf
                        @method('post')

                        @include('admin.partials._errors')

                        {{--category_id--}}
                        <div class="form-group">
                            <label>@lang('categories.category') <span class="text-danger">*</span></label>
                            <select name="category_id" class="form-control select2">
                                <option value="">@lang('site.choose') @lang('categories.category')</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}" {{ $category->id == old('category_id') ? 'selected' : '' }}>{{ $category->title }}</option>
                                @endforeach
                            </select>
                        </div>

                        {{--title--}}
                        <div class="form-group">
                            <label>@lang('articles.title') <span class="text-danger">*</span></label>
                            <input type="text" name="title" class="form-control" value="{{ old('title') }}" autofocus required>
                        </div>

                        {{--body--}}
                        <div class="form-group">
                            <label>@lang('articles.body') <span class="text-danger">*</span></label>
                            <textarea name="body" class="form-control ckeditor">{{ old('body') }}</textarea>
                        </div>

                        {{--image--}}
                        <div class="form-group">
                            <label>@lang('categories.image') <span class="text-danger">*</span></label>
                            <input type="file" name="image" class="form-control load-image" required>
                            <img src="" class="loaded-image" alt="" style="display: none; width: 200px; margin: 10px 0;">
                        </div>

                        {{--file--}}
                        <div class="form-group">
                            <label>@lang('articles.file') <span class="text-danger">*</span></label>
                            <input type="file" name="file" class="form-control load-image">
                        </div>

                        {{--time_to_read--}}
                        <div class="form-group">
                            <label>@lang('articles.time_to_read')</label>
                            <input type="number" name="time_to_read" class="form-control" value="{{ old('time_to_read') }}">
                        </div>

                        {{--status--}}
                        <div class="form-group">
                            <label>@lang('articles.status') <span class="text-danger">*</span></label>
                            <select name="status" class="form-control select2" required>
                                <option value="">@lang('site.choose') @lang('articles.status')</option>
                                <option value="published">@lang('articles.published')</option>
                                <option value="unpublished">@lang('articles.unpublished')</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-info"><i class="fa fa-plus"></i> @lang('site.create')</button>
                        </div>

                    </form><!-- end of form -->

                </div><!-- end  card body-->

            </div><!-- end of card -->

        </div><!-- end of row -->
@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2 pt-2">@lang('articles.articles')</h2>

    <ul class="breadcrumb my-2">
        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.articles.index') }}">@lang('articles.articles')</a></li>
        <li class="breadcrumb-item">@lang('site.edit')</li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <form method="post" action="{{ route('admin.articles.update', $article->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('put')

                        @include('admin.partials._errors')

                        {{--category_id--}}
                        <div class="form-group">
                            <label>@lang('categories.category') <span class="text-danger">*</span></label>
                            <select name="category_id" class="form-control select2">
                                <option value="">@lang('site.choose') @lang('categories.category')</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}" {{ $category->id == old('category_id', $article->category_id) ? 'selected' : '' }}>{{ $category->title }}</option>
                                @endforeach
                            </select>
                        </div>

                        {{--title--}}
                        <div class="form-group">
                            <label>@lang('articles.title') <span class="text-danger">*</span></label>
                            <input type="text" name="title" class="form-control" value="{{ old('title', $article->title) }}" autofocus required>
                        </div>

                        {{--body--}}
                        <div class="form-group">
                            <label>@lang('articles.body') <span class="text-danger">*</span></label>
                            <textarea name="body" class="form-control ckeditor">{{ old('body', $article->body) }}</textarea>
                        </div>

                        {{--image--}}
                        <div class="form-group">
                            <label>@lang('categories.image') <span class="text-danger">*</span></label>
                            <input type="file" name="image" class="form-control load-image">
                            <img src="{{ $article->image_path }}" class="loaded-image" alt="" style="display: block; width: 200px; margin: 10px 0;">
                        </div>

                        {{--file--}}
                        <div class="form-group">
                            <label>@lang('articles.file')</label>
                            <input type="file" name="file" class="form-control load-image">
                        </div>

                        {{--time_to_read--}}
                        <div class="form-group">
                            <label>@lang('articles.time_to_read')</label>
                            <input type="number" name="time_to_read" class="form-control" value="{{ old('time_to_read', $article->time_to_read) }}">
                        </div>

                        {{--status--}}
                        <div class="form-group">
                            <label>@lang('articles.status') <span class="text-danger">*</span></label>
                            <select name="status" class="form-control select2" required>
                                <option value="">@lang('site.choose') @lang('articles.status')</option>
                                <option value="published" {{ $article->status == 'published' ? 'selected' : '' }}>@lang('articles.published')</option>
                                <option value="unpublished" {{ $article->status == 'unpublished' ? 'selected' : '' }}>@lang('articles.unpublished')</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-info"><i class="fa fa-edit"></i> @lang('site.update')</button>
                        </div>

                    </form><!-- end of form -->

                </div><!-- end of card body -->

            </div><!-- end of card -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2 pt-2">@lang('articles.articles')</h2>

    <ul class="breadcrumb my-2">
        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
        <li class="breadcrumb-item">@lang('articles.articles')</li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <div class="row mb-3">

                        <div class="col-md-12">

                            @if (auth()->user()->hasPermission('read_articles'))
                                <a href="{{ route('admin.articles.create') }}" class="btn btn-info"><i class="fa fa-plus"></i> @lang('site.create')</a>
                            @endif

                            @if (auth()->user()->hasPermission('delete_articles'))
                                <form method="post" action="{{ route('admin.articles.bulk_delete') }}" style="display: inline-block;">
                                    @csrf
                                    @method('delete')
                                    <input type="hidden" name="record_ids" id="record-ids">
                                    <button type="submit" class="btn btn-danger" id="bulk-delete" disabled="true"><i class="fa fa-trash"></i> @lang('site.bulk_delete')</button>
                                </form><!-- end of form -->
                            @endif

                        </div>

                    </div><!-- end of row -->

                    <div class="row">

                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" id="data-table-search" class="form-control" autofocus placeholder="@lang('site.search')">
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <select id="status" class="form-control select2">
                                    <option value="">@lang('site.all') @lang('articles.statuses')</option>
                                    <option value="published">@lang('articles.published')</option>
                                    <option value="unpublished">@lang('articles.unpublished')</option>
                                </select>
                            </div>
                        </div>

                    </div><!-- end of row -->

                    <div class="row">

                        <div class="col-md-12">

                            <div class="table-responsive">

                                <table class="table datatable" id="articles-table" style="width: 100%;">
                                    <thead>
                                    <tr>
                                        <th>
                                            <input type="checkbox" id="record__select-all"/>
                                            <label for="record__select-all"></label>
                                        </th>
                                        <th>@lang('articles.title')</th>
                                        <th>@lang('articles.status')</th>
                                        <th>@lang('site.created_at')</th>
                                        <th style="width: 20%;">@lang('site.action')</th>
                                    </tr>
                                    </thead>
                                </table>

                            </div><!-- end of table responsive -->

                        </div><!-- end of col -->

                    </div><!-- end of row -->

                </div><!-- end of card body -->

            </div><!-- end of card -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

@push('scripts')

    <script>

        let status;
        let category = "{{ request()->category_id }}"

        let articlesTable = $('#articles-table').DataTable({
            dom: "tiplr",
            serverSide: true,
            processing: true,
            "language": {
                "url": "{{ asset('admin_assets/datatable-lang/' . app()->getLocale() . '.json') }}"
            },
            ajax: {
                url: '{{ route('admin.articles.data') }}',
                data: function (d) {
                    d.status = status;
                    d.category_id = category;
                }
            },
            columns: [
                {data: 'record_select', name: 'record_select', searchable: false, sortable: false, width: '1%'},
                {data: 'title', name: 'title'},
                {data: 'status', name: 'status'},
                {data: 'created_at', name: 'created_at', searchable: false},
                {data: 'actions', name: 'actions', searchable: false, sortable: false},
            ],
            order: [[3, 'desc']],
            drawCallback: function (settings) {
                $('.record__select').prop('checked', false);
                $('#record__select-all').prop('checked', false);
                $('#record-ids').val();
                $('#bulk-delete').attr('disabled', true);
            }
        });

        $('#status').on('change', function () {
            status = this.value;
            articlesTable.ajax.reload();
        });

        $('#data-table-search').keyup(function () {
            articlesTable.search(this.value).draw();
        })
    </script>

@endpush

resources/views/admin/articles/show.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2 pt-2">@lang('articles.articles')</h2>

    <ul class="breadcrumb my-2">
        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.articles.index') }}">@lang('articles.articles')</a></li>
        <li class="breadcrumb-item">@lang('site.show')</li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <table class="table table-hover">

                        <tr>
                            <th style="width: 15%;">@lang('categories.category')</th>
                            <td>{{ $article->category->title }}</td>
                        </tr>

                        <tr>
                            <th style="width: 15%;">@lang('articles.title')</th>
                            <td>{{ $article->title }}</td>
                        </tr>

                        <tr>
                            <th style="width: 15%;">@lang('articles.body')</th>
                            <td>{!! $article->body !!}</td>
                        </tr>

                        <tr>
                            <th style="width: 15%;">@lang('articles.image')</th>
                            <td><img src="{{ $article->image_path }}" style="width: 200px;" alt=""></td>
                        </tr>

                        <tr>
                            <th style="width: 15%;">@lang('articles.file')</th>
                            <td><a href="{{ $article->file_path }}" target="_blank" class="btn btn-info btn-sm"><i class="fa fa-download"></i> @lang('site.download')</a></td>
                        </tr>

                        <tr>
                            <th style="width: 15%;">@lang('articles.time_to_read')</th>
                            <td>{{ $article->time_to_read }}</td>
                        </tr>

                        <tr>
                            <th style="width: 15%;">@lang('articles.status')</th>
                            <td>@lang('articles.' . $article->status)</td>
                        </tr>

                    </table>

                </div><!-- end of card body -->

            </div><!-- end of card -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection