routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//category routes
Route::get('/categories/{category}/general_overview', 'CategoryController@generalOverview')->name('categories.general_overview');
Route::resource('categories', 'CategoryController')->only(['index']);

//article routes
Route::resource('articles', 'ArticleController')->only(['index', 'show']);

//contact us request routes
Route::resource('contact_us_requests', 'ContactUsRequestController')->only(['store']);

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Article extends Model
{
    use HasFactory;

    protected $fillable = ['category_id', 'title', 'body', 'image', 'file', 'time_to_read', 'status', 'views_count'];
    protected $appends = ['file_path', 'image_path'];

    //attr
    public function getFilePathAttribute()
    {
        return Storage::url('uploads/' . $this->file);

    }// end of getFilePathAttribute

    public function getImagePathAttribute()
    {
        return Storage::url('uploads/' . $this->image);

    }// end of getFilePathAttribute

    //scope
    public function scopeWhenStatus($query, $status)
    {
        return $query->when($status, function ($q) use ($status) {

            return $q->where('status', $status);

        });

    }// end of scopeWhenStatus

    public function scopeWhenCategoryId($query, $categoryId)
    {
        return $query->when($categoryId, function ($q) use ($categoryId) {

            return $q->where('category_id', $categoryId);

        });

    }// end of scopeWhenCategoryId

    public function scopeWhenSearch($query, $search)
    {
        return $query->when($search, function ($q) use ($search) {

            return $q->where('title', 'like', "%$search%");

        });

    }// end of scopeWhenSearch

    //rel
    public function category()
    {
        return $this->belongsTo(Category::class);

    }// end of category

}//end of model

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ArticleRequest;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class ArticleController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read_articles')->only(['index']);
        $this->middleware('permission:create_articles')->only(['create', 'store']);
        $this->middleware('permission:update_articles')->only(['edit', 'update']);
        $this->middleware('permission:delete_articles')->only(['delete', 'bulk_delete']);

    }// end of __construct

    public function index()
    {
        return view('admin.articles.index');

    }// end of index

    public function data()
    {
        $articles = Article::whenStatus(request()->status)
            ->whenCategoryId(request()->category_id)
            ->select();

        return DataTables::of($articles)
            ->addColumn('record_select', 'admin.articles.data_table.record_select')
            ->addColumn('status', 'admin.articles.data_table.status')
            ->editColumn('created_at', function (Article $article) {
                return $article->created_at->format('Y-m-d');
            })
            ->addColumn('actions', 'admin.articles.data_table.actions')
            ->rawColumns(['record_select', 'status', 'actions'])
            ->toJson();


    }// end of data

    public function create()
    {
        $categories = Category::all();

        return view('admin.articles.create', compact('categories'));

    }// end of create

    public function store(ArticleRequest $request)
    {
        $requestData = $request->validated();

        if ($request->file) {
            $request->file->store('public/uploads');
            $requestData['file'] = $request->file->hashName();
        }

        if ($request->image) {
            $request->image->store('public/uploads');
            $requestData['image'] = $request->image->hashName();
        }

        Article::create($requestData);

        session()->flash('success', __('site.added_successfully'));
        return redirect()->route('admin.articles.index');

    }// end of store

    public function show(Article $article)
    {
        return view('admin.articles.show', compact('article'));

    }// end of show

    public function edit(Article $article)
    {
        $categories = Category::all();

        return view('admin.articles.edit', compact('categories', 'article'));

    }// end of edit

    public function update(ArticleRequest $request, Article $article)
    {
        $requestData = $request->validated();

        if ($request->file) {
            Storage::disk('local')->delete('public/uploads/' . $article->file);
            $request->file->store('public/uploads');
            $requestData['file'] = $request->file->hashName();
        }

        if ($request->image) {
            Storage::disk('local')->delete('public/uploads/' . $article->image);
            $request->image->store('public/uploads');
            $requestData['image'] = $request->image->hashName();
        }

        $article->update($requestData);

        session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('admin.articles.index');

    }// end of update

    public function destroy(Article $article)
    {
        $this->delete($article);
        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('admin.articles.index');

    }// end of destroy

    public function bulkDelete()
    {
        foreach (json_decode(request()->record_ids) as $recordId) {

            $article = Article::FindOrFail($recordId);
            $this->delete($article);

        }//end of for each

        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('admin.articles.index');

    }// end of bulkDelete

    private function delete(Article $article)
    {
        $article->delete();

    }// end of delete

}///end of controller

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Category;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::whenCategoryId(request()->category_id)
            ->whenSearch(request()->search)
            ->where('status', 'published')
            ->paginate(10);

        $this->incrementCategoryViews();

        $category = null;
        $otherCategories = null;

        if (request()->category_id) {

            $category = Category::FindOrFail(request()->category_id);

            $otherCategories = Category::where('id', '!=', $category->id)->limit(4)->get();

        }

        return view('articles.index', compact('category', 'articles', 'otherCategories'));

    }// end of index

    public function show(Article $article)
    {
        $this->incrementArticleViews($article);
        return view('articles.show', compact('article'));

    }// end of show

    private function incrementCategoryViews()
    {
        if (request()->category_id) {
            $category = Category::FindOrFail(request()->category_id);
            $category->increment('views_count');
        }

    }// end of incrementCategoryViews

    private function incrementArticleViews(Article $article)
    {
        $article->increment('views_count');

    }// end of incrementCategoryViews

}//end of controller

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')

    @if ($category)

        @include('layouts._banner_inner', ['category' => $category, 'background' => $category->image_path, 'title' => $category->title, 'body' => $category->body])

    @else

        @include('layouts._banner_inner', ['background' => '/assets/images/categories-image.jpg', 'title' => __('site.search_results'), 'body' => __('site.search_by_using_search_bar')])

    @endif

    <section id="categories" class="py-5">

        <div class="container">

            <div class="row py-3">

                @if ($articles->count() > 0)

                    <div class="{{ $otherCategories ? 'col-md-9' : 'col-md-12' }}">

                        @foreach ($articles as $article)

                            <div class="row article">

                                <div class="col-md-3">
                                    <a href="{{ $article->file_path }}" target="_blank">
                                        <img src="{{ $article->image_path }}" class="img-fluid card-img-top mb-3" alt="">
                                    </a>
                                </div>

                                <div class="col-md-8">
                                    <h4 class="article-title">{{ $article->title }}</h4>
                                    <p class="article-text">{!! $article->body !!}</p>
                                    <div class="d-flex justify-content-between category-info">
                                        <span><i class="fab fa-readme"></i> {{ $article->time_to_read }} @lang('articles.time_to_read') </span>
                                        <span><i class="fa fa-eye"></i> {{ $article->views_count }}  @lang('site.views')</span>
                                    </div>
                                </div>

                            </div><!-- end of row -->

                        @endforeach

                        {{ $articles->appends(request()->query())->links() }}

                    </div><!-- end of col -->

                    @if ($otherCategories)

                        <div class="col-md-3">
                            <h3>@lang('categories.other_categories')</h3>

                            @foreach ($otherCategories as $otherCategory)

                                <div class="row mb-3">

                                    <div class="col-md-12">

                                        <div class="card">

                                            <a href="{{ route('articles.index', ['category_id' => $otherCategory->id]) }}" class="category-card-image-wrapper">
                                                <img src="{{ $otherCategory->image_path }}" class="category-card-image img-fluid card-img-top" alt="">
                                            </a>

                                            <div class="card-body">
                                                <h5 class="mb-1">{{ $otherCategory->title }}</h5>
                                                <p style="font-size: 14px;">{!! $otherCategory->text !!}</p>
                                                <div class="d-flex justify-content-between category-info">
                                                    <span style="font-size: 14px;"><i class="fa fa-file"></i> {{ $otherCategory->articles->count() }} @lang('articles.articles')</span>
                                                    <span style="font-size: 14px;"><i class="fa fa-eye"></i> {{ $otherCategory->views_count }} @lang('site.views')</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            @endforeach

                            <a href="{{ route('categories.index') }}">@lang('site.show_more')</a>
                        </div>

                    @endif

                @else
                    <div class="col-md-12 text-center">
                        <i class="fa fa-times-circle mb-4" style="font-size: 35px;"></i>
                        <h4>@lang('site.no_data_found')</h4>
                    </div>
                @endif

            </div><!-- end of row -->

        </div><!-- end of container -->

    </section>

@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')

    @include('layouts._banner_inner', ['background' => $article->image_path, 'title' => $article->title])

    <section id="categories" class="py-5">

        <div class="container">

            <div class="row py-3">

                <div class="col-dm-12">

                    <h3>{{ $article->title }}</h3>
                    <hr>

                    <div class="d-flex category-info mb-3">
                        <span><i class="fab fa-readme"></i> {{ $article->time_to_read }} @lang('articles.time_to_read') </span>
                        <span class="mx-3"><i class="fa fa-eye"></i> {{ $article->views_count }} @lang('site.views')</span>
                    </div>

                    {!! $article->body !!}

                    <a href="{{ $article->file_path }}" target="_blank" class="btn btn-primary"><i class="fa fa-download"></i> @lang('articles.download_attached_files')</a>

                </div>

            </div><!-- end of row -->

        </div><!-- end of container -->

    </section>

@endsection