routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//category routes
Route::get('/categories/{category}/general_overview', 'CategoryController@generalOverview')->name('categories.general_overview');
Route::resource('categories', 'CategoryController')->only(['index']);

//article routes
Route::resource('articles', 'ArticleController')->only(['index', 'show']);

//contact us request routes
Route::resource('contact_us_requests', 'ContactUsRequestController')->only(['store']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'body', 'general_overview', 'image', 'views_count'];
    protected $appends = ['image_path'];

    //attr
    public function getImagePathAttribute()
    {
        return Storage::url('uploads/' . $this->image);

    }// end of getImagePathAttribute

    //scope

    //rel
    public function articles()
    {
        return $this->hasMany(Article::class);

    }// end of articles

}//end of model

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CategoryRequest;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read_categories')->only(['index']);
        $this->middleware('permission:create_categories')->only(['create', 'store']);
        $this->middleware('permission:update_categories')->only(['edit', 'update']);
        $this->middleware('permission:delete_categories')->only(['delete', 'bulk_delete']);

    }// end of __construct

    public function index()
    {
        return view('admin.categories.index');

    }// end of index

    public function data()
    {
        $categories = Category::withCount(['articles']);

        return DataTables::of($categories)
            ->addColumn('record_select', 'admin.categories.data_table.record_select')
            ->addColumn('articles', 'admin.categories.data_table.articles')
            ->editColumn('created_at', function (Category $category) {
                return $category->created_at->format('Y-m-d');
            })
            ->addColumn('actions', 'admin.categories.data_table.actions')
            ->rawColumns(['record_select', 'articles', 'actions'])
            ->toJson();


    }// end of data

    public function create()
    {
        return view('admin.categories.create');

    }// end of create

    public function store(CategoryRequest $request)
    {
        $requestData = $request->validated();

        if ($request->image) {
            $request->image->store('public/uploads');
            $requestData['image'] = $request->image->hashName();
        }

        Category::create($requestData);

        session()->flash('success', __('site.added_successfully'));
        return redirect()->route('admin.categories.index');

    }// end of store

    public function show(Category $category)
    {
        return view('admin.categories.show', compact('category'));

    }// end of show

    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));

    }// end of edit

    public function update(CategoryRequest $request, Category $category)
    {
        $requestData = $request->validated();

        if ($request->image) {
            Storage::disk('local')->delete('public/uploads/' . $category->image);
            $request->image->store('public/uploads');
            $requestData['image'] = $request->image->hashName();
        }

        $category->update($requestData);

        session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('admin.categories.index');

    }// end of update

    public function destroy(Category $category)
    {
        $this->delete($category);
        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('admin.categories.index');

    }// end of destroy

    public function bulkDelete()
    {
        foreach (json_decode(request()->record_ids) as $recordId) {

            $category = Category::FindOrFail($recordId);
            $this->delete($category);

        }//end of for each

        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('admin.categories.index');

    }// end of bulkDelete

    private function delete(Category $category)
    {
        Storage::disk('local')->delete('public/uploads/' . $category->image);
        $category->delete();

    }// end of delete

}//end of controller

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::paginate(12);
        return view('categories.index', compact('categories'));

    }// end of index

    public function show(Category $category)
    {
        return view('categories.show', compact('category'));

    }// end of show

    public function generalOverview(Category $category)
    {
        $otherCategories = Category::where('id', '!=', $category->id)->limit(4)->get();

        return view('categories.general_overview', compact('category', 'otherCategories'));

    }// end of generalOverview

}//end of controller

resources/views/admin/categories/create.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2 pt-2">@lang('categories.categories')</h2>

    <ul class="breadcrumb my-2">
        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.categories.index') }}">@lang('categories.categories')</a></li>
        <li class="breadcrumb-item">@lang('site.create')</li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <form method="post" action="{{ route('admin.categories.store') }}" enctype="multipart/form-data">
                        @csrf
                        @method('post')

                        @include('admin.partials._errors')

                        {{--title--}}
                        <div class="form-group">
                            <label>@lang('categories.title') <span class="text-danger">*</span></label>
                            <input type="text" name="title" class="form-control" value="{{ old('title') }}" autofocus required>
                        </div>

                        {{--body--}}
                        <div class="form-group">
                            <label>@lang('categories.body') <span class="text-danger">*</span></label>
                            <textarea name="body" class="form-control ckeditor" required>{{ old('body') }}</textarea>
                        </div>

                        {{--general_overview--}}
                        <div class="form-group">
                            <label>@lang('categories.general_overview') <span class="text-danger">*</span></label>
                            <textarea name="general_overview" class="form-control ckeditor">{{ old('general_overview') }}</textarea>
                        </div>

                        {{--image--}}
                        <div class="form-group">
                            <label>@lang('categories.image') <span class="text-danger">*</span></label>
                            <input type="file" name="image" class="form-control load-image" required>
                            <img src="" class="loaded-image" alt="" style="display: none; width: 200px; margin: 10px 0;">
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-info"><i class="fa fa-plus"></i> @lang('site.create')</button>
                        </div>

                    </form><!-- end of form -->

                </div><!-- end  card body-->

            </div><!-- end of card -->

        </div><!-- end of row -->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2 pt-2">@lang('categories.categories')</h2>

    <ul class="breadcrumb my-2">
        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.categories.index') }}">@lang('categories.categories')</a></li>
        <li class="breadcrumb-item">@lang('site.edit')</li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <form method="post" action="{{ route('admin.categories.update', $category->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('put')

                        @include('admin.partials._errors')

                        {{--title--}}
                        <div class="form-group">
                            <label>@lang('categories.title') <span class="text-danger">*</span></label>
                            <input type="text" name="title" class="form-control" value="{{ old('title', $category->title) }}" autofocus required>
                        </div>

                        {{--body--}}
                        <div class="form-group">
                            <label>@lang('categories.body') <span class="text-danger">*</span></label>
                            <textarea name="body" class="form-control ckeditor" required>{{ old('body', $category->body) }}</textarea>
                        </div>

                        {{--general_overview--}}
                        <div class="form-group">
                            <label>@lang('categories.general_overview') <span class="text-danger">*</span></label>
                            <textarea name="general_overview" class="form-control ckeditor">{{ old('general_overview', $category->general_overview) }}</textarea>
                        </div>

                        {{--image--}}
                        <div class="form-group">
                            <label>@lang('categories.image') <span class="text-danger">*</span></label>
                            <input type="file" name="image" class="form-control load-image">
                            <img src="{{ $category->image_path }}" class="loaded-image" alt="" style="display: block; width: 200px; margin: 10px 0;">
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-info"><i class="fa fa-edit"></i> @lang('site.update')</button>
                        </div>

                    </form><!-- end of form -->

                </div><!-- end of card body -->

            </div><!-- end of card -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2 pt-2">@lang('categories.categories')</h2>

    <ul class="breadcrumb my-2">
        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
        <li class="breadcrumb-item">@lang('categories.categories')</li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <div class="row mb-3">

                        <div class="col-md-12">

                            @if (auth()->user()->hasPermission('read_categories'))
                                <a href="{{ route('admin.categories.create') }}" class="btn btn-info"><i class="fa fa-plus"></i> @lang('site.create')</a>
                            @endif

                            @if (auth()->user()->hasPermission('delete_categories'))
                                <form method="post" action="{{ route('admin.categories.bulk_delete') }}" style="display: inline-block;">
                                    @csrf
                                    @method('delete')
                                    <input type="hidden" name="record_ids" id="record-ids">
                                    <button type="submit" class="btn btn-danger" id="bulk-delete" disabled="true"><i class="fa fa-trash"></i> @lang('site.bulk_delete')</button>
                                </form><!-- end of form -->
                            @endif

                        </div>

                    </div><!-- end of row -->

                    <div class="row">

                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" id="data-table-search" class="form-control" autofocus placeholder="@lang('site.search')">
                            </div>
                        </div>

                    </div><!-- end of row -->

                    <div class="row">

                        <div class="col-md-12">

                            <div class="table-responsive">

                                <table class="table datatable" id="categories-table" style="width: 100%;">
                                    <thead>
                                    <tr>
                                        <th>
                                            <input type="checkbox" id="record__select-all"/>
                                            <label for="record__select-all"></label>
                                        </th>
                                        <th>@lang('categories.title')</th>
                                        <th>@lang('categories.articles_count')</th>
                                        <th>@lang('articles.articles')</th>
                                        <th>@lang('site.created_at')</th>
                                        <th style="width: 20%;">@lang('site.action')</th>
                                    </tr>
                                    </thead>
                                </table>

                            </div><!-- end of table responsive -->

                        </div><!-- end of col -->

                    </div><!-- end of row -->

                </div><!-- end of card body -->

            </div><!-- end of card -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

@push('scripts')

    <script>

        let categoriesTable = $('#categories-table').DataTable({
            dom: "tiplr",
            serverSide: true,
            processing: true,
            "language": {
                "url": "{{ asset('admin_assets/datatable-lang/' . app()->getLocale() . '.json') }}"
            },
            ajax: {
                url: '{{ route('admin.categories.data') }}',
            },
            columns: [
                {data: 'record_select', name: 'record_select', searchable: false, sortable: false, width: '1%'},
                {data: 'title', name: 'title'},
                {data: 'articles_count', name: 'articles_count', searchable: false},
                {data: 'articles', name: 'articles', searchable: false, sortable: false},
                {data: 'created_at', name: 'created_at', searchable: false},
                {data: 'actions', name: 'actions', searchable: false, sortable: false},
            ],
            order: [[4, 'desc']],
            drawCallback: function (settings) {
                $('.record__select').prop('checked', false);
                $('#record__select-all').prop('checked', false);
                $('#record-ids').val();
                $('#bulk-delete').attr('disabled', true);
            }
        });

        $('#data-table-search').keyup(function () {
            categoriesTable.search(this.value).draw();
        })
    </script>

@endpush

resources/views/admin/categories/show.blade.php
@extends('layouts.admin.app')

@section('content')

    <h2 class="mb-2 pt-2">@lang('categories.categories')</h2>

    <ul class="breadcrumb my-2">
        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">@lang('site.home')</a></li>
        <li class="breadcrumb-item"><a href="{{ route('admin.categories.index') }}">@lang('categories.categories')</a></li>
        <li class="breadcrumb-item">@lang('site.show')</li>
    </ul>

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <table class="table table-hover">
                        <tr>
                            <th style="width: 15%;">@lang('categories.title')</th>
                            <td>{{ $category->title }}</td>
                        </tr>

                        <tr>
                            <th style="width: 15%;">@lang('categories.body')</th>
                            <td>{!! $category->body !!}</td>
                        </tr>

                        <tr>
                            <th style="width: 15%;">@lang('categories.image')</th>
                            <td><img src="{{ $category->image_path }}" style="width: 200px;" alt=""></td>
                        </tr>

                    </table>

                </div><!-- end of card body -->

            </div><!-- end of card -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection